name: gw
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.43.2
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.1.3
  - python=3.9.18
  - readline=8.2
  - setuptools=68.2.2
  - tk=8.6.13
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.2.6
  - pip=21.3.1
  - pip:
      - absl-py==2.0.0
      - audioread==3.0.1
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==5.1.1
      - filelock==3.12.4
      - fonttools==4.43.1
      - fsspec==2023.9.2
      - grpcio==1.59.0
      - idna==3.4
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - librosa==0.9.1
      - llvmlite==0.41.0
      - markdown==3.5
      - markupsafe==2.1.3
      - matplotlib==3.1.3
      - mpmath==1.3.0
      - networkx==3.1
      - numba==0.58.0
      - numpy==1.22.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.2.140
      - nvidia-nvtx-cu12==12.1.105
      - packaging==23.2
      - pillow==10.1.0
      - pip==21.3.1
      - platformdirs==3.11.0
      - pooch==1.7.0
      - protobuf==3.20.3
      - pycparser==2.21
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - requests==2.31.0
      - resampy==0.4.2
      - scikit-learn==1.3.1
      - scipy==1.5.1
      - six==1.16.0
      - soundfile==0.12.1
      - sympy==1.12
      - tensorboard==2.0.0
      - threadpoolctl==3.2.0
      - torch==2.1.0
      - torchsummary==1.5.1
      - triton==2.1.0
      - typing-extensions==4.8.0
      - urllib3==2.0.6
      - werkzeug==3.0.0
      - zipp==3.17.0